/**
 * The single source of truth for every failure Axon can name. One flat map,
 * one entry per unique failure — codes are never reused and never change
 * once shipped (a code is a stable identity a user or a support thread can
 * reference). New failures get an entry here before their call site exists;
 * `err()` refuses to compile against a code this map doesn't declare.
 *
 * `title`/`description` are the rendering contract: title is a short,
 * user-facing headline ("Agent failed to start"), description is one or two
 * sentences of plain-language context — not the message, not the stack.
 * Both are written for someone who has never read this codebase.
 *
 * `severity` replaces a bare recoverable boolean — a degrading-but-handled
 * failure and a fatal one both need to reach the log, just not with the
 * same weight:
 *   - "fatal"      — the operation this belongs to did not complete. Always logged, always rendered loud.
 *   - "recovered"  — failed, but a fallback/retry made it survivable. Logged for visibility, not alarmed.
 *   - "degraded"   — the system continues in a lesser state (a feature disabled, a cache miss that will retry). Logged, low urgency.
 */

// AxonErrorSource / AxonErrorSeverity are the wire contract — they live in
// @arcforge/types and are re-exported here so this map's entries and existing
// importers resolve them from the same place.
export type { AxonErrorSource, AxonErrorSeverity } from "@arcforge/types"
import type { AxonErrorSource, AxonErrorSeverity } from "@arcforge/types"

export type AxonErrorMapEntry = {
    /** Stable short code, e.g. "AX-BOOT-001". Never reused, never renumbered. */
    code: string
    /** Short, user-facing headline. */
    title: string
    /** One or two plain-language sentences — what happened and why it matters, not a stack dump. */
    description: string
    source: AxonErrorSource
    severity: AxonErrorSeverity
}

/**
 * This map must be updated for every unique failure case.
 */
export const errorMap = {
    UNKNOWN: {
        code: "AX-UNKNOWN-001",
        title: "Unclassified Error",
        description: "An error occurred that hasn't been given a proper code yet. This is itself worth fixing — see the err(cause) call site that produced it.",
        source: "runtime",
        severity: "fatal",
    },
    PROMPT_NOT_FOUND: {
        code: "AX-PROMPT-001",
        title: "Prompt Not Found",
        description: "The requested prompt was not found in the agent's blueprint. It may not be declared, or the agent needs to be re-prepared.",
        source: "runtime",
        severity: "fatal",
    },
    PROMPT_FILE_NOT_FOUND: {
        code: "AX-PROMPT-002",
        title: "Prompt File Missing",
        description: "The prompt is declared but its source file no longer exists on disk.",
        source: "runtime",
        severity: "fatal",
    },
    PROMPT_RENDER_FAILED: {
        code: "AX-PROMPT-003",
        title: "Prompt Render Failed",
        description: "The prompt's source file failed to compile or render — likely a malformed SFC (content outside <template>/<script>/<style>) or an error thrown while rendering. See the cause for the underlying parser/render error.",
        source: "runtime",
        severity: "fatal",
    },
    SCRIPT_NOT_FOUND: {
        code: "AX-SCRIPT-001",
        title: "Script Not Found",
        description: "The requested script was not found in the agent's blueprint. It may not be declared, or the agent needs to be re-prepared.",
        source: "runtime",
        severity: "fatal",
    },
    SCRIPT_FILE_NOT_FOUND: {
        code: "AX-SCRIPT-002",
        title: "Script File Missing",
        description: "The script is declared but its source file no longer exists on disk.",
        source: "runtime",
        severity: "fatal",
    },
    ENGINE_MISSING: {
        code: "AX-ENGINE-001",
        title: "No Engine Configured",
        description: "The agent's blueprint has no engine — it cannot dispatch to a model. Set `engine` in axon.config.ts.",
        source: "runtime",
        severity: "fatal",
    },
    INJECT_OUTSIDE_RUNTIME: {
        code: "AX-RUNTIME-001",
        title: "Runtime Accessed Before Boot",
        description: "A runtime global (axon, args) was read before the runtime finished booting.",
        source: "runtime",
        severity: "fatal",
    },
    BOOT_FAILED: {
        code: "AX-BOOT-001",
        title: "Agent Failed To Start",
        description: "The agent's runtime crashed while starting, before it could accept requests.",
        source: "runtime",
        severity: "fatal",
    },
    BOOT_SCRIPT_FAILED: {
        code: "AX-BOOT-002",
        title: "Boot Script Failed",
        description: "The agent's boot.vue threw while rendering — check the script setup block for the error.",
        source: "runtime",
        severity: "fatal",
    },
    BOOT_SCRIPT_INVALID: {
        code: "AX-BOOT-003",
        title: "Boot Script Malformed",
        description: "The agent's boot.vue has content outside its recognized <script>/<template> blocks, or otherwise failed to parse as a valid SFC.",
        source: "runtime",
        severity: "fatal",
    },

    // ── Cognet (host.ts / cognet.ts) ────────────────────────────────────────
    COGNET_ACCESSED_BEFORE_LOAD: {
        code: "AX-COGNET-001",
        title: "Cognet Accessed Before Load",
        description: "A cognet global (kernel, phase, system, blueprint) was read before the brain finished loading, or outside the loop body that owns it.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_LOOP_ALREADY_DECLARED: {
        code: "AX-COGNET-002",
        title: "Loop Already Declared",
        description: "A cognet's main() called loop() more than once — the loop is the program's entire main body and can only be declared once.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_ALREADY_LOADED: {
        code: "AX-COGNET-003",
        title: "Cognet Bound To A Different Kernel",
        description: "This cognet instance already loaded against a different kernel ABI — a reload produced a conflicting bind instead of a clean swap.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_NO_LOOP: {
        code: "AX-COGNET-004",
        title: "Cognet Declared No Loop",
        description: "The cognet's main() ran (or was woken) without ever declaring loop() — there is no program to run.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_MAX_TICKS: {
        code: "AX-COGNET-005",
        title: "Cognet Exceeded Max Ticks",
        description: "The cognet's loop ran more ticks in one wake than its configured limit allows — likely a runaway loop that never calls stop().",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_ABI_MISMATCH: {
        code: "AX-COGNET-006",
        title: "Cognet ABI Mismatch",
        description: "The compiled cognet targets a kernel ABI version the running kernel doesn't provide — rebuild the cognet against the current framework version.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_MISSING: {
        code: "AX-COGNET-007",
        title: "No Compiled Cognet",
        description: "The blueprint points at a compiled cognet bundle that doesn't exist on disk yet — run `axon prepare` before booting.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_HASH_MISMATCH: {
        code: "AX-COGNET-008",
        title: "Cognet Bundle Hash Mismatch",
        description: "The compiled cognet bundle on disk doesn't match the hash the blueprint expects — it's stale or was tampered with. Run `axon prepare` again.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_INVALID: {
        code: "AX-COGNET-009",
        title: "Invalid Cognet Bundle",
        description: "The compiled cognet's default export isn't a real cognet definition — the compile step produced something malformed.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_IDENTITY_MISMATCH: {
        code: "AX-COGNET-010",
        title: "Cognet Identity Mismatch",
        description: "The compiled cognet artifact's own name doesn't match what the blueprint declared — the wrong bundle may be at this path.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_CONFIG_MISSING: {
        code: "AX-COGNET-011",
        title: "Cognet Config Missing",
        description: "No cognet.config.ts was found in the cognet's source directory — every cognet needs one to declare its identity.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_BUILD_FAILED: {
        code: "AX-COGNET-012",
        title: "Cognet Failed To Compile",
        description: "Bundling the cognet's source into a runnable artifact failed — check the build log for the underlying syntax or import error.",
        source: "cognet",
        severity: "fatal",
    },
    COGNET_NOT_FOUND: {
        code: "AX-COGNET-013",
        title: "Cognet Not Found",
        description: "The cognet named by `cognet:` in axon.config.ts could not be located. The detail says where it was looked for — a registry that answered 404, or a node_modules tree it was missing from. Check the specifier for a typo, and check which registry the CLI is pointed at (AXON_API_BASE).",
        source: "cognet",
        severity: "fatal",
    },

    // ── Project (build/project/) ────────────────────────────────────────────
    MODULE_SPECIFIER_INVALID: {
        code: "AX-PROJECT-005",
        title: "Invalid Module Specifier",
        description: "Module names must be scoped as @scope/name. The registry does not accept unscoped packages, so an unscoped specifier can never resolve.",
        source: "manifest",
        severity: "fatal",
    },
    CONFIG_MODULES_UNPARSEABLE: {
        code: "AX-PROJECT-006",
        title: "Could Not Edit axon.config.ts",
        description: "The install succeeded but the module entry could not be written into the config's modules array automatically — add or remove it by hand.",
        source: "manifest",
        severity: "fatal",
    },
    CONFIG_ENGINE_UNPARSEABLE: {
        code: "AX-PROJECT-033",
        title: "Could Not Edit The Engine In axon.config.ts",
        description: "The agent's `engine: X({ ... })` declaration could not be located or rewritten automatically — set the model by hand.",
        source: "manifest",
        severity: "fatal",
    },
    MODULE_DEPENDENCY_INSTALL_FAILED: {
        code: "AX-PROJECT-004",
        title: "Module Dependencies Failed To Install",
        description: "The module source was downloaded, but its npm dependencies could not be materialized for the agent. Resolve the package-manager error and run the install again.",
        source: "manifest",
        severity: "fatal",
    },

    // ── Blueprint (build/blueprint/blueprint.ts) ────────────────────────────
    BLUEPRINT_NOT_LOADED: {
        code: "AX-PROJECT-002",
        title: "Blueprint Accessed Before Load",
        description: "Something read the blueprint's current value before load() had ever run.",
        source: "manifest",
        severity: "fatal",
    },
    AGENT_INVALID: {
        code: "AX-PROJECT-003",
        title: "Invalid Agent Directory",
        description: "The agent root has no package.json — every agent is a real package, this one isn't.",
        source: "manifest",
        severity: "fatal",
    },
    CORRUPT_JSON: {
        code: "AX-PROJECT-016",
        title: "Corrupt JSON File",
        description: "A stored JSON file failed to parse — it may have been hand-edited into an invalid state, or a write was interrupted mid-flight.",
        source: "manifest",
        severity: "fatal",
    },
    FILE_UNREADABLE: {
        code: "AX-PROJECT-032",
        title: "File Could Not Be Read",
        description: "A file exists but could not be read — most often a permissions problem, a directory where a file was expected, or a disk error. Distinct from a missing file, which is an ordinary absent-surface state.",
        source: "manifest",
        severity: "fatal",
    },
    PROVIDER_NOT_CONNECTED: {
        code: "AX-TUI-011",
        title: "Provider Not Connected",
        description: "The selected model routes through a provider (OpenRouter, Codex) that isn't connected yet — connect it before picking a model on that route.",
        source: "tui",
        severity: "fatal",
    },
    PALETTE_INPUT_REQUIRED: {
        code: "AX-TUI-012",
        title: "Required Input Missing",
        description: "A palette command needs a value for this field before it can run.",
        source: "tui",
        severity: "fatal",
    },
    BENCH_NO_CASES: {
        code: "AX-TUI-013",
        title: "Bench Declared No Cases",
        description: "The bench's test file ran to completion under Bun but never declared a single benchmark case.",
        source: "tui",
        severity: "fatal",
    },

    // ── Project (build/project/*.ts) ────────────────────────────────────────
    PROJECT_NOT_FOUND: {
        code: "AX-PROJECT-017",
        title: "Project Not Found",
        description: "No axon.config.ts, module.config.ts, cognet.config.ts, bench.config.ts, or prompt.config.ts was found at this path — it isn't a recognized project directory.",
        source: "manifest",
        severity: "fatal",
    },
    PROJECT_WRONG_KIND: {
        code: "AX-PROJECT-011",
        title: "Wrong Project Kind",
        description: "This command targets one project kind, and the directory holds another — run the command that matches what is actually here.",
        source: "manifest",
        severity: "fatal",
    },
    PROJECT_EXISTS: {
        code: "AX-PROJECT-018",
        title: "Project Already Exists",
        description: "Scaffolding refused to overwrite a directory that already exists — remove it or pick a different name first.",
        source: "manifest",
        severity: "fatal",
    },
    TYPEGEN_NO_BLUEPRINT: {
        code: "AX-PROJECT-007",
        title: "Typegen Needs A Loaded Blueprint",
        description: "Agent-kind typegen was called without a blueprint — its declared surfaces are the source of the generated types.",
        source: "manifest",
        severity: "fatal",
    },
    DEPLOY_AGENTS_ONLY: {
        code: "AX-PROJECT-008",
        title: "Only Agents Can Deploy",
        description: "A module was asked to deploy on its own — modules only run installed inside an agent, deploy the agent instead.",
        source: "manifest",
        severity: "fatal",
    },
    PUBLISH_UNSUPPORTED_KIND: {
        code: "AX-PROJECT-009",
        title: "This Project Kind Cannot Publish Yet",
        description: "Only agents and modules publish to the registry today. Cognets and benches become first-class registry artifacts in the unified artifact work — until then, publishing one would register it under the wrong kind and claim its name in the shared namespace.",
        source: "manifest",
        severity: "fatal",
    },
    MODEL_SPECIFIER_INVALID: {
        code: "AX-MODEL-001",
        title: "Malformed Model Specifier",
        description: "A `models:` entry in cognet.config.ts could not be parsed. The short form is `hf:owner/repo/path/to/file` — a repo alone is ambiguous, since one repo holds many weights.",
        source: "manifest",
        severity: "fatal",
    },
    MODEL_FETCH_FAILED: {
        code: "AX-MODEL-002",
        title: "Model Weights Could Not Be Fetched",
        description: "A declared model could not be downloaded. Check the repo, file path and revision, and that the machine can reach the registry. A brain without its weights is broken rather than degraded, so this fails at prepare instead of at first inference.",
        source: "manifest",
        severity: "fatal",
    },
    MODEL_HASH_MISMATCH: {
        code: "AX-MODEL-003",
        title: "Model Weights Failed Verification",
        description: "Downloaded bytes did not hash to the expected value — the upstream file changed, or the download was corrupted. Nothing is cached: storing unverified weights would make every later run trust them.",
        source: "manifest",
        severity: "fatal",
    },
    MODEL_NOT_CACHED: {
        code: "AX-MODEL-004",
        title: "Declared Model Is Not Cached",
        description: "`--frozen` asserts the machine is already provisioned, so it will not fetch. Run `axon prepare` without --frozen to populate the model cache.",
        source: "manifest",
        severity: "fatal",
    },
    PREPARE_FROZEN_DRIFT: {
        code: "AX-PROJECT-014",
        title: "Dependencies Drifted From The Lockfile",
        description: "`--frozen` asserts that package.json, the lockfile and node_modules already agree. Something did not: a dependency is missing, at a version outside its declared range, or declared but no longer selected. Run `axon prepare` without --frozen to reconcile, and commit the result.",
        source: "manifest",
        severity: "fatal",
    },
    PUBLISH_VERIFY_FAILED: {
        code: "AX-PROJECT-013",
        title: "Artifact Does Not Compile",
        description: "The package was built, but compiling it the way a consumer would failed — so publishing it would ship something nobody can install. Usually a file the source imports was left out of the package. Published versions are immutable, so this is caught before upload rather than after.",
        source: "manifest",
        severity: "fatal",
    },
    DEPLOY_PROVISION_FAILED: {
        code: "AX-PROJECT-012",
        title: "Deployment Provisioning Failed",
        description: "The agent was published, but the cloud control plane could not provision its runtime. The request ID identifies the server-side failure.",
        source: "manifest",
        severity: "fatal",
    },
    DEPLOY_RUNTIME_FAILED: {
        code: "AX-PROJECT-013",
        title: "Agent Failed To Start",
        description: "Cloud infrastructure was provisioned, but the agent process failed during boot. The reported runtime diagnostic identifies the immediate cause.",
        source: "runtime",
        severity: "fatal",
    },
    DEPLOY_ENV_RESERVED: {
        code: "AX-PROJECT-014",
        title: "Reserved Deployment Variable",
        description: "The production .env file attempts to override a variable owned by the Axon runtime or Cloud Run.",
        source: "manifest",
        severity: "fatal",
    },
    DEPLOY_ENV_INVALID: {
        code: "AX-PROJECT-015",
        title: "Invalid Deployment Variable",
        description: "The production .env file contains a key that is not a valid environment variable name.",
        source: "manifest",
        severity: "fatal",
    },
    BUNDLE_MODULE_COLLISION: {
        code: "AX-PROJECT-019",
        title: "Module Name Collision",
        description: "A hard-imported source module's name collides with an already-installed registry module of the same name.",
        source: "manifest",
        severity: "fatal",
    },
    BUNDLE_INVALID: {
        code: "AX-PROJECT-010",
        title: "Invalid Bundle Source",
        description: "The directory being bundled has no package.json, or its package.json has no name — every bundle needs a real package identity.",
        source: "manifest",
        severity: "fatal",
    },
    BUNDLE_TAR_MISSING: {
        code: "AX-PROJECT-020",
        title: "tar Not Found",
        description: "Bundling shells out to the system's tar binary, which isn't on PATH — install Git for Windows or use WSL on that platform.",
        source: "manifest",
        severity: "fatal",
    },
    BUNDLE_TAR_FAILED: {
        code: "AX-PROJECT-021",
        title: "tar Failed",
        description: "The tar subprocess exited non-zero while building a bundle archive.",
        source: "manifest",
        severity: "fatal",
    },

    // ── Bench (build/bench/*.ts) ────────────────────────────────────────────
    BENCH_RUN_NOT_FOUND: {
        code: "AX-BENCH-001",
        title: "Bench Run Not Found",
        description: "No recorded bench run exists with this id.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_NOT_FOUND: {
        code: "AX-BENCH-002",
        title: "Bench Not Found",
        description: "No bench.config.ts was found at this path — it isn't a recognized bench project.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_TESTS_NOT_FOUND: {
        code: "AX-BENCH-003",
        title: "Bench Test Files Not Found",
        description: "The bench config declares test files that don't exist on disk.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_LOCAL_REF_NOT_FOUND: {
        code: "AX-BENCH-004",
        title: "Bench Local Reference Not Found",
        description: "A factor variable references a local file/directory that doesn't exist.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_CONFIG_INVALID: {
        code: "AX-BENCH-005",
        title: "Bench Config Invalid",
        description: "bench.config.ts failed to evaluate or didn't produce a valid bench definition.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_PACKAGE_NOT_FOUND: {
        code: "AX-BENCH-006",
        title: "Bench Package Not Found",
        description: "No package.json exists at the bench root — every bench project needs one for identity.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_PACKAGE_NAME_REQUIRED: {
        code: "AX-BENCH-007",
        title: "Bench Package Name Required",
        description: "The bench's package.json has no name field.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_PACKAGE_VERSION_REQUIRED: {
        code: "AX-BENCH-008",
        title: "Bench Package Version Required",
        description: "The bench's package.json has no version field.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_CONTEXT_MISSING: {
        code: "AX-BENCH-009",
        title: "Bench Context Missing",
        description: "The benchmark preload needs AXON_BENCH_CONTEXT set — it was run outside the bench harness.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_NO_ACTIVE_CASE: {
        code: "AX-BENCH-010",
        title: "No Active Bench Case",
        description: "A bench emission (measurement, artifact) happened outside any running Bun test — these calls must occur inside a test case.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_WORKSPACE_UNAVAILABLE: {
        code: "AX-BENCH-011",
        title: "Bench Workspace Unavailable",
        description: "The bench's workspace directory hasn't been materialized yet for this run.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_AGENT_UNRESOLVED: {
        code: "AX-BENCH-012",
        title: "Bench Agent Unresolved",
        description: "The bench's declared subject agent isn't a prepared local agent — run `axon prepare` on it first.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_MEASUREMENT_UNKNOWN: {
        code: "AX-BENCH-013",
        title: "Unknown Bench Measurement",
        description: "A measurement was emitted under an id the bench config never declared.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_MEASUREMENT_TYPE: {
        code: "AX-BENCH-014",
        title: "Bench Measurement Type Mismatch",
        description: "A measurement's emitted value doesn't match the type its bench config declaration expects.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_MEASUREMENT_DOMAIN: {
        code: "AX-BENCH-015",
        title: "Bench Measurement Out Of Domain",
        description: "A measurement's emitted value falls outside the range or category the bench config declares for it.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_DIMENSION_UNKNOWN: {
        code: "AX-BENCH-016",
        title: "Unknown Bench Dimension",
        description: "A dimension value was set under an id the bench config never declared.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_DIMENSION_DOMAIN: {
        code: "AX-BENCH-017",
        title: "Bench Dimension Out Of Domain",
        description: "A dimension's set value isn't one of the categories its bench config declares.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_AXIS_UNKNOWN: {
        code: "AX-BENCH-018",
        title: "Unknown Bench Factor",
        description: "Something referenced a factor id the running bench's coordinate never assigned a value to.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_ARTIFACT_UNKNOWN: {
        code: "AX-BENCH-019",
        title: "Unknown Bench Artifact",
        description: "An artifact was emitted under an id the bench config never declared.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_ARTIFACT_MEDIA_TYPE: {
        code: "AX-BENCH-020",
        title: "Bench Artifact Media Type Not Allowed",
        description: "An artifact was emitted with a media type its bench config declaration doesn't allow.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_SCHEMA_UNREADABLE: {
        code: "AX-BENCH-030",
        title: "Bench Schema Unreadable",
        description: "bench.config.ts could not be parsed while extracting the measurement schema.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_SCHEMA_EMPTY: {
        code: "AX-BENCH-031",
        title: "Bench Schema Empty",
        description: "defineBench<Schema> was given a type with no properties — an empty schema and a failed extraction must never look alike.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_SCHEMA_UNSUPPORTED_TYPE: {
        code: "AX-BENCH-032",
        title: "Bench Measurement Type Unsupported",
        description: "A measurement is not a boolean, number, union of string literals, or string.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_SCHEMA_EXTRACTION_FAILED: {
        code: "AX-BENCH-033",
        title: "Bench Schema Extraction Failed",
        description: "The schema worker did not return a schema. Prepare fails rather than continuing with an empty one, which would silently make every measurement undeclared.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_AXIS_NOT_FOUND: {
        code: "AX-BENCH-021",
        title: "Bench Axis Not Found",
        description: "The bench config's matrix has no axis with this key.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_AXIS_VALUE_NOT_FOUND: {
        code: "AX-BENCH-022",
        title: "Bench Axis Value Not Found",
        description: "The bench config's matrix axis has no declared value with this id.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_WORKSPACE_ESCAPE: {
        code: "AX-BENCH-023",
        title: "Bench Workspace Path Escapes Root",
        description: "A workspace source entry resolved to a path outside the workspace directory — refused rather than materialized.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_WORKSPACE_SYMLINK_UNSUPPORTED: {
        code: "AX-BENCH-024",
        title: "Bench Workspace Symlinks Unsupported",
        description: "A workspace source contains a symlink — not supported when materializing a bench workspace.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_WORKSPACE_OUTSIDE_ROOT: {
        code: "AX-BENCH-025",
        title: "Bench Template Outside Root",
        description: "A workspace template's declared source path resolves outside the bench project root.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_WORKSPACE_SOURCE_NOT_FOUND: {
        code: "AX-BENCH-026",
        title: "Bench Template Not Found",
        description: "A workspace template's declared source path isn't a real directory.",
        source: "bench",
        severity: "fatal",
    },
    BENCH_LOG_INVALID: {
        code: "AX-BENCH-027",
        title: "Bench Log Invalid",
        description: "A bench run's event log is missing an entry its projection requires — the log is incomplete or was written out of order.",
        source: "bench",
        severity: "fatal",
    },

    // ── Blueprint scan (scan/tools.ts, scan/config.ts) ──────────────────────
    TOOL_DECLARE_FAILED: {
        code: "AX-BLUEPRINT-002",
        title: "Tool Declaration Failed",
        description: "Compiling a src/tools/*.ts file's TypeScript declarations failed — the worker subprocess reported a compile error.",
        source: "manifest",
        severity: "fatal",
    },
    TOOL_BUNDLE_FAILED: {
        code: "AX-BLUEPRINT-006",
        title: "Tool Bundle Failed",
        description: "Bundling a src/tools/*.ts file to self-contained source failed — the bundler subprocess reported an error. Tools are bundled so the sandbox loads them without mounting the project; a bundle failure means the tool cannot enter the box.",
        source: "manifest",
        severity: "fatal",
    },
    ROUTE_LOAD_FAILED: {
        code: "AX-BLUEPRINT-007",
        title: "Route Load Failed",
        description: "A file in server/api/ could not be imported. The agent would serve an endpoint set that is not the declared one — a caller gets a 404 for a route whose file exists.",
        source: "manifest",
        severity: "fatal",
    },
    SCRIPT_LOAD_FAILED: {
        code: "AX-BLUEPRINT-008",
        title: "Script Load Failed",
        description: "A file in src/scripts/ could not be processed. `axon run <name>` would report the script as not found while its file sits in the project.",
        source: "manifest",
        severity: "fatal",
    },
    PLUGIN_LOAD_FAILED: {
        code: "AX-BLUEPRINT-009",
        title: "Plugin Load Failed",
        description: "A plugin could not be imported. Plugins wire server behaviour at boot; one silently missing means the agent runs without behaviour its author declared.",
        source: "manifest",
        severity: "fatal",
    },
    MIDDLEWARE_LOAD_FAILED: {
        code: "AX-BLUEPRINT-010",
        title: "Middleware Load Failed",
        description: "A middleware file could not be imported. Middleware commonly carries auth and validation, so a silently skipped one is a request path running without the checks its author wrote.",
        source: "manifest",
        severity: "fatal",
    },
    PROMPT_INTROSPECT_FAILED: {
        code: "AX-BLUEPRINT-011",
        title: "Prompt Introspection Failed",
        description: "A .vue prompt could not be introspected for its props. The prompt would render without the inputs it declares, or not at all.",
        source: "manifest",
        severity: "fatal",
    },
    CONFIG_NOT_FOUND: {
        code: "AX-BLUEPRINT-003",
        title: "Config Not Found",
        description: "No axon.config.ts exists at this path.",
        source: "manifest",
        severity: "fatal",
    },
    CONFIG_LOAD_FAILED: {
        code: "AX-BLUEPRINT-004",
        title: "Config Failed To Load",
        description: "axon.config.ts threw or failed to evaluate — check the file for a syntax or runtime error.",
        source: "manifest",
        severity: "fatal",
    },
    CONFIG_INVALID: {
        code: "AX-BLUEPRINT-005",
        title: "Config Invalid",
        description: "axon.config.ts evaluated but never called defineAgent() — every agent config must produce one.",
        source: "manifest",
        severity: "fatal",
    },

    // ── Kernel (engine.ts / executor.ts) ─────────────────────────────────────
    ENGINE_NO_DONE: {
        code: "AX-KERNEL-001",
        title: "Engine Stream Ended Without Completing",
        description: "The model driver's stream ended without ever emitting a completion event — the engine likely disconnected or crashed mid-response.",
        source: "kernel",
        severity: "fatal",
    },
    ENGINE_STREAM_FAILED: {
        code: "AX-KERNEL-008",
        title: "Engine Stream Failed",
        description: "The model driver's stream failed and exhausted its retries (or the failure wasn't retryable) — see context for the provider's fault code.",
        source: "kernel",
        severity: "fatal",
    },
    CODEX_NOT_CONNECTED: {
        code: "AX-KERNEL-012",
        title: "Codex Subscription Not Connected",
        description: "This agent uses a Codex model, but your Axon account is not connected to ChatGPT — run :provider codex connect and try again.",
        source: "kernel",
        severity: "fatal",
    },
    RUN_IN_PROGRESS: {
        code: "AX-KERNEL-002",
        title: "A Wake Is Already Running",
        description: "The kernel only executes one wake at a time — a new run was requested while the previous one was still active.",
        source: "kernel",
        severity: "recovered",
    },
    RUN_RESERVATION_EXPIRED: {
        code: "AX-KERNEL-003",
        title: "Wake Reservation Expired",
        description: "The reserved execution slot for this wake is no longer active — it was released before the run could start.",
        source: "kernel",
        severity: "fatal",
    },
    NO_COGNET_LOADED: {
        code: "AX-KERNEL-004",
        title: "No Cognet Loaded",
        description: "The kernel tried to execute a wake, but the blueprint carried no cognet definition to run it against.",
        source: "kernel",
        severity: "fatal",
    },
    SYSCALL_OUTSIDE_RUN: {
        code: "AX-KERNEL-005",
        title: "Syscall Outside An Active Run",
        description: "A kernel syscall (engine.stream and similar) was made with no active wake to attribute it to.",
        source: "kernel",
        severity: "fatal",
    },
    CAPSULE_ACCESSED_BEFORE_BOOT: {
        code: "AX-KERNEL-007",
        title: "Capsule Accessed Before Boot",
        description: "Something reached for the live capsule instance before boot() had run — there is no sandbox yet to hand back.",
        source: "kernel",
        severity: "fatal",
    },
    COGNET_EMIT_FORBIDDEN: {
        code: "AX-KERNEL-009",
        title: "Cognet Emit Forbidden",
        description: "A cognet tried to emit an event outside the cognet:* namespace — the ABI only lets a cognet narrate its own telemetry, never forge kernel machinery events.",
        source: "kernel",
        severity: "fatal",
    },
    SCHEDULER_MODE_MISMATCH: {
        code: "AX-KERNEL-010",
        title: "Scheduler Mode Mismatch",
        description: "A caller used the wrong wake verb for the cognet's mode: continuous cognets advance via tick(), driven by the body's clock; invocation cognets wake on a stimulus via request()/stream().",
        source: "kernel",
        severity: "fatal",
    },

    // ── Session (session.ts) ─────────────────────────────────────────────────
    THREAD_UNKNOWN_PARENT: {
        code: "AX-SESSION-001",
        title: "Thread Branched From Unknown Parent",
        description: "A thread's recorded lineage points at a parent thread id that isn't registered in this session — the session index is inconsistent.",
        source: "thread",
        severity: "fatal",
    },
    THREAD_NOT_FOUND: {
        code: "AX-SESSION-002",
        title: "Thread Not Found",
        description: "The requested thread id isn't registered in this session.",
        source: "thread",
        severity: "fatal",
    },
    THREAD_BRANCH_UNKNOWN: {
        code: "AX-SESSION-003",
        title: "Cannot Branch Unknown Thread",
        description: "A branch was requested from a parent thread id that isn't registered in this session.",
        source: "thread",
        severity: "fatal",
    },

    // ── Blueprint ─────────────────────────────────────────────────────────────
    NO_COGNET: {
        code: "AX-BLUEPRINT-001",
        title: "No Cognet Declared",
        description: "The blueprint carries no cognet definition — an agent cannot run without a brain. The CLI or test harness must construct and pass one.",
        source: "runtime",
        severity: "fatal",
    },

    // ── Control channel ───────────────────────────────────────────────────────
    // The local socket between a running TUI and the Fleet extension. Both
    // ends dispatch by walking a property path against the handle the peer
    // exposed, so a bad path is the channel's characteristic failure.
    CONTROL_PATH_NOT_FOUND: {
        code: "AX-CONTROL-001",
        title: "Control Path Not Found",
        description: "A control-channel call named a method the peer does not expose. The two ends disagree about the surface — usually a TUI and an extension built from different versions.",
        source: "server",
        severity: "fatal",
    },
    CONTROL_PATH_NOT_CALLABLE: {
        code: "AX-CONTROL-002",
        title: "Control Path Not Callable",
        description: "A control-channel call resolved to a value on the peer's handle that is not a function.",
        source: "server",
        severity: "fatal",
    },
    CONTROL_CALL_FAILED: {
        code: "AX-CONTROL-003",
        title: "Control Call Failed",
        description: "The peer served a control-channel call and it threw. The remote message is carried here — the failure surfaces at the local call site rather than being returned as a falsy value.",
        source: "server",
        severity: "fatal",
    },
    CONTROL_CLOSED: {
        code: "AX-CONTROL-004",
        title: "Control Channel Closed",
        description: "A control-channel call was made, or was still in flight, when the channel closed. In-flight calls reject on close rather than hanging forever on an answer that is no longer coming.",
        source: "server",
        severity: "fatal",
    },
    CONTROL_UNAUTHORIZED: {
        code: "AX-CONTROL-005",
        title: "Control Handshake Rejected",
        description: "A connection to the control socket presented a missing or incorrect token. The token lives in the instance record, which is readable only by the owning user — a mismatch means the caller is not the local Fleet extension.",
        source: "server",
        severity: "fatal",
    },

    // ── Server ────────────────────────────────────────────────────────────────
    PLUGIN_BOOT_FAILED: {
        code: "AX-SERVER-001",
        title: "Plugin Failed During Boot",
        description: "A server plugin threw while running at boot — plugins are the one place in server startup where a failure must abort the boot rather than being warned and skipped.",
        source: "server",
        severity: "fatal",
    },
    HANDLE_SHUTDOWN_FAILED: {
        code: "AX-RUNTIME-002",
        title: "Handle Failed To Shut Down",
        description: "One of the runtime's owned handles (kernel, etc.) threw during shutdown — teardown is error-isolated, so the others still ran, but this one didn't close cleanly.",
        source: "runtime",
        severity: "fatal",
    },
    BUS_HANDLER_FAILED: {
        code: "AX-RUNTIME-004",
        title: "Bus Handler Failed",
        description: "A handler subscribed to a runtime bus event threw. Handler failures are non-fatal by design — the remaining handlers still run — but they are recorded rather than swallowed, since plugins and modules register handlers and a silently-broken one is invisible rot.",
        source: "runtime",
        severity: "degraded",
    },
    TOOL_CALL_FAILED: {
        code: "AX-RUNTIME-003",
        title: "Tool Call Failed",
        description: "An axon.tools.<namespace>.<fn>() call from script-land completed with a non-ok result from the capsule — unwrapped here into a normal throw, since script-land expects the ordinary call/throw contract, not the kernel's own stable-result shape.",
        source: "runtime",
        severity: "fatal",
    },

    // ── Capsule (build/tools.ts) ─────────────────────────────────────────────
    CAPSULE_TOOL_TIMEOUT: {
        code: "AX-CAPSULE-001",
        title: "Tool Load Timed Out",
        description: "The sandbox never confirmed loading a declared tool within the timeout — it may be stuck on a slow import or the subprocess is unresponsive.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_TOOL_SCOPE_MISMATCH: {
        code: "AX-CAPSULE-002",
        title: "Tool Scope Mismatch",
        description: "A tool's declared exports don't match what it actually exported once loaded in the sandbox — the bundled source and its declaration have drifted apart.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_TOOL_FAILED: {
        code: "AX-CAPSULE-003",
        title: "Tool Failed To Load",
        description: "A declared tool failed to load into the sandbox — its source may be malformed, too large to import, or the subprocess exited before confirming.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_CONFINE_UNAVAILABLE: {
        code: "AX-CAPSULE-004",
        title: "OS Confinement Unavailable",
        description: "The policy requested OS confinement (isolation: auto) but the host is missing a required primitive (bubblewrap, systemd, nft, or the axon-agent user). Run `axon install`, or set isolation: none to opt out explicitly. The capsule refuses to boot rather than silently run unconfined.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_CONFINE_USER_UNRESOLVED: {
        code: "AX-CAPSULE-005",
        title: "Confinement User Unresolved",
        description: "The confinement user exists but its numeric uid/gid could not be read — the box cannot drop privileges without them. The host user database may be inconsistent.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_BOOT_FAILED: {
        code: "AX-CAPSULE-006",
        title: "Capsule Failed To Boot",
        description: "The sandbox subprocess exited or reported failure before completing the boot handshake. The captured stderr in the error context is the real cause — most often a confinement mount that could not be satisfied (a declared fs path that does not exist) or a runtime that could not start.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_BOOT_TIMEOUT: {
        code: "AX-CAPSULE-007",
        title: "Capsule Boot Timed Out",
        description: "The sandbox subprocess did not report ready within the boot timeout. Its captured stderr is in the error context; if empty, the subprocess may be hung rather than crashed.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_SPAWN_FAILED: {
        code: "AX-CAPSULE-008",
        title: "Capsule Spawn Failed",
        description: "The capsule subprocess command could not be spawned at all — the interpreter or confinement wrapper was not found, or PATH is unset. Check that bun (and, under confinement, bwrap/systemd-run) are on PATH.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_WIRE_CLOSED: {
        code: "AX-CAPSULE-009",
        title: "Capsule Wire Closed",
        description: "A command was sent to the sandbox after its stdin pipe was gone — the subprocess has exited or is mid-teardown. The caller is racing the capsule lifecycle.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_DOWN: {
        code: "AX-CAPSULE-010",
        title: "No Live Capsule",
        description: "An operation needed a running sandbox subprocess, but none is live — it is booting, restarting after a crash, or has been declared dead.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_ALREADY_BOOTED: {
        code: "AX-CAPSULE-011",
        title: "Capsule Already Booted",
        description: "boot() was called on a capsule that already has a live subprocess. Boot is once per lifetime; use update()/reload() to replace a running incarnation.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_INSTALL_FAILED: {
        code: "AX-CAPSULE-013",
        title: "Confinement Install Failed",
        description: "Provisioning the host for the hardened confinement tier failed — most often because creating the dedicated system user needs root. Re-run `axon install` with sufficient privilege.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_HOST_UNAVAILABLE: {
        code: "AX-CAPSULE-014",
        title: "Host Bridge Unavailable",
        description: "Sandboxed code called a host service, but this capsule was built with no host provider. Host calls require a wired host bridge on the manager side.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_CRASHED: {
        code: "AX-CAPSULE-015",
        title: "Capsule Crashed",
        description: "An unhandled error escaped inside the sandbox subprocess. The capsule reports it on the wire and exits immediately — after an unhandled throw the sandbox's state is unknown, and a capsule that keeps serving is worse than one that dies loudly.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_DEAD: {
        code: "AX-CAPSULE-016",
        title: "Capsule Dead",
        description: "The capsule subprocess is gone and supervision gave up restarting it. Every subsequent execution request fails until a new capsule is booted.",
        source: "capsule",
        severity: "fatal",
    },
    CAPSULE_PARSE_ERROR: {
        code: "AX-CAPSULE-017",
        title: "Capsule Wire Parse Error",
        description: "A line arriving from the sandbox was not a valid protocol event. The sandbox is speaking garbage — a protocol mismatch or corrupted output — and the line is dropped rather than acted on, never silently.",
        source: "capsule",
        severity: "degraded",
    },
    CAPSULE_CMD_FAILED: {
        code: "AX-CAPSULE-018",
        title: "Capsule Command Failed",
        description: "Code executed in the sandbox threw. This is the ordinary failure path for an agent-emitted block or a script-land run() — the error is the sandboxed code's own, surfaced verbatim.",
        source: "capsule",
        severity: "degraded",
    },
    CAPSULE_FN_FAILED: {
        code: "AX-CAPSULE-019",
        title: "Tool Call Threw",
        description: "A mediated tool function threw inside the sandbox. The failure is the tool's own; it propagates to the calling code unchanged and is recorded as the closing half of the call's span.",
        source: "capsule",
        severity: "degraded",
    },
    CAPSULE_PROC_DENIED: {
        code: "AX-CAPSULE-020",
        title: "Process Spawn Denied",
        description: "A process the sandbox tried to start was refused — denied by policy, killed before it could spawn, or the spawn itself failed. No process was created.",
        source: "capsule",
        severity: "degraded",
    },
    CAPSULE_PROC_FAILED: {
        code: "AX-CAPSULE-022",
        title: "Managed Process Failed",
        description: "A spawned child process errored without ever producing an exit code — an exec failure or a broken IPC channel. Distinct from a non-zero exit, which is the process running correctly and reporting a result.",
        source: "capsule",
        severity: "degraded",
    },
    CAPSULE_PROC_STDIN_FAILED: {
        code: "AX-CAPSULE-021",
        title: "Process Stdin Write Failed",
        description: "Writing to a managed child process's stdin failed — the process is no longer running, or its stdin has already closed.",
        source: "capsule",
        severity: "degraded",
    },

    // ── TUI (useAgents.ts / platform/build/runtime / platform/store / platform/services/cloud) ──
    NOT_BOOTED: {
        code: "AX-TUI-001",
        title: "No Agent Running",
        description: "A message was sent, or an action requiring a live agent was taken, before any agent finished booting.",
        source: "tui",
        severity: "fatal",
    },
    NOT_AUTHENTICATED: {
        code: "AX-TUI-002",
        title: "Not Logged In",
        description: "The action needs an active profile, but none is logged in yet.",
        source: "tui",
        severity: "fatal",
    },
    PROFILE_NOT_AUTHENTICATED: {
        code: "AX-TUI-003",
        title: "Profile Has No Session",
        description: "The target profile exists but has no stored session — it has never logged in, or its session was cleared.",
        source: "tui",
        severity: "fatal",
    },
    PROFILE_UNKNOWN: {
        code: "AX-TUI-004",
        title: "Unknown Profile",
        description: "The requested profile id isn't one of the profiles stored on this machine.",
        source: "tui",
        severity: "fatal",
    },
    SESSION_ALREADY_RUNNING: {
        code: "AX-TUI-005",
        title: "Session Is Already Running",
        description: "spawn() was asked to resume a session that already has a live instance. Focus the running instance instead of booting a second runtime over the same log.",
        source: "tui",
        severity: "fatal",
    },
    SESSION_NOT_RUNNING: {
        code: "AX-TUI-016",
        title: "Session Is Not Running",
        description: "focus() was pointed at a sessionId with no live instance behind it. Spawn (or resume) it first — focus is pure selection over running instances.",
        source: "tui",
        severity: "fatal",
    },
    NO_FOCUSED_INSTANCE: {
        code: "AX-TUI-017",
        title: "No Focused Agent Instance",
        description: "A module install/uninstall was requested with no running agent instance focused — spawn or focus one first.",
        source: "tui",
        severity: "fatal",
    },
    MODEL_IMMUTABLE_DEPLOYED: {
        code: "AX-TUI-006",
        title: "Cannot Change A Deployment's Model",
        description: "A deployed agent's config lives in the cloud, not on this machine — its model is fixed at deploy time. Change it in the local project and deploy again.",
        source: "tui",
        severity: "fatal",
    },
    MODULE_INSTALL_FAILED: {
        code: "AX-TUI-018",
        title: "Module Install Failed",
        description: "The registry installer returned an error for this module specifier — check the specifier and registry connectivity.",
        source: "tui",
        severity: "fatal",
    },
    NO_MODULES_INSTALLED: {
        code: "AX-TUI-019",
        title: "No Modules Installed",
        description: "The :uninstall command was opened with no modules resolved into the focused instance's blueprint.",
        source: "tui",
        severity: "fatal",
    },
    DEPLOYMENT_NOT_CONNECTABLE: {
        code: "AX-TUI-028",
        title: "Deployment Not Connectable",
        description: "The deployment is not in the connectable list — it may have stopped, errored, or never finished provisioning. Refresh the deployment list and try again.",
        source: "tui",
        severity: "fatal",
    },
    SUBAGENT_REMOTE_PARENT: {
        code: "AX-TUI-027",
        title: "Cannot Spawn A Subagent From A Deployment",
        description: "A subagent is forked from its parent's local project, and an attached deployment has no local project here — the deployed agent runs its own subagents inside its own capsule.",
        source: "tui",
        severity: "fatal",
    },
    BASE_MODEL_INSTANCE_CONFLICT: {
        code: "AX-TUI-026",
        title: "Managed Model Instance Already Running",
        description: "A managed base instance is already running on a different engine. The base workspace holds one shared config, so spawning a second naked model would rewrite it underneath the live instance — close the running one first.",
        source: "tui",
        severity: "fatal",
    },
    NOT_WIRED: {
        code: "AX-TUI-008",
        title: "Not Wired Yet",
        description: "This surface is a declared stub — the real implementation hasn't been built yet.",
        source: "tui",
        severity: "fatal",
    },
    MIC_ALREADY_CAPTURING: {
        code: "AX-TUI-009",
        title: "Mic Already Capturing",
        description: "capture.start() was called while a capture was already in progress — stop the current one first.",
        source: "tui",
        severity: "fatal",
    },
    MIC_CAPTURE_UNAVAILABLE: {
        code: "AX-TUI-010",
        title: "No Audio Capture Tool Found",
        description: "Voice input needs one of arecord, sox, or ffmpeg installed and on PATH.",
        source: "tui",
        severity: "fatal",
    },
    MIC_FFT_SIZE_MISMATCH: {
        code: "AX-TUI-014",
        title: "FFT Sample Size Mismatch",
        description: "computeBuckets() was called with a sample buffer that isn't exactly config.fftSize long — an internal invariant, callers must pad/trim first.",
        source: "tui",
        severity: "fatal",
    },
    MIC_CAPTURE_FAILED: {
        code: "AX-TUI-015",
        title: "Mic Capture Failed",
        description: "The audio capture subprocess produced no output or exited immediately — check that a microphone is available.",
        source: "tui",
        severity: "fatal",
    },
    WATCH_PATH_REQUIRED: {
        code: "AX-TUI-021",
        title: "Watch Path Required",
        description: "`axon watch`/`axon unwatch` need a directory argument.",
        source: "tui",
        severity: "fatal",
    },
    WATCH_PATH_NOT_FOUND: {
        code: "AX-TUI-022",
        title: "Watch Path Not Found",
        description: "`axon watch` was given a directory that doesn't exist on disk.",
        source: "tui",
        severity: "fatal",
    },
    EDITOR_NOT_SET: {
        code: "AX-TUI-023",
        title: "No Editor Configured",
        description: "`axon settings` needs the $EDITOR environment variable set to know which editor to open.",
        source: "tui",
        severity: "fatal",
    },
    EDITOR_LAUNCH_FAILED: {
        code: "AX-TUI-024",
        title: "Editor Failed To Launch",
        description: "The command in $EDITOR could not be spawned — check that it's installed and on PATH.",
        source: "tui",
        severity: "fatal",
    },
    WATCH_AND_INIT_ARGS_REQUIRED: {
        code: "AX-TUI-025",
        title: "Directory And Name Required",
        description: "The init palette's \"watch a new directory\" entry needs both a directory path and an agent name, space-separated.",
        source: "tui",
        severity: "fatal",
    },

    // ── Module boot-time execution (core runs defineModule setup) ────────────
    MODULE_CONFIG_LOAD_FAILED: {
        code: "AX-MODULE-001",
        title: "Module Config Failed To Load",
        description: "The runtime could not import a module's module.config.ts at boot — the file is missing at its resolved path, or importing it threw. A module that cannot load contributes nothing, so boot fails rather than run a partially-wired agent.",
        source: "runtime",
        severity: "fatal",
    },
    MODULE_OPTIONS_INVALID: {
        code: "AX-MODULE-002",
        title: "Invalid Module Options",
        description: "The options declared for a module under modules.<name> in axon.config.ts do not satisfy the module's options schema — a required option is missing or a value has the wrong type.",
        source: "runtime",
        severity: "fatal",
    },
    MODULE_SETUP_FAILED: {
        code: "AX-MODULE-003",
        title: "Module Setup Failed",
        description: "A module's setup() threw during agent boot. Setup runs sequentially in blueprint order and a failure is total — no later module is wired, and the agent does not boot half-configured.",
        source: "runtime",
        severity: "fatal",
    },
    MODULE_SERVER_NOT_WIRED: {
        code: "AX-MODULE-004",
        title: "Module Server API Not Wired",
        description: "A module's setup() called ctx.server.addRoute/addMiddleware or ctx.tools.get, but that surface is not implemented yet. Declare routes as server/api/ files in the module instead.",
        source: "runtime",
        severity: "fatal",
    },
    MODULE_ENV_REQUIRED: {
        code: "AX-MODULE-005",
        title: "Module Env Var Missing",
        description: "A module's setup() called ctx.env.require() for a variable the agent's resolved environment does not provide. The module declares required env in module.config.ts; the agent must supply it (e.g. in .env).",
        source: "runtime",
        severity: "fatal",
    },
    MODULE_POLICY_IMMUTABLE: {
        code: "AX-MODULE-006",
        title: "Module Policy Is Immutable At Boot",
        description: "A module's setup() called ctx.policy.update(). The resolved agent policy is authoritative and cannot be mutated at boot — declare policy needs statically in module.config.ts so the CLI reconciles them at install.",
        source: "runtime",
        severity: "fatal",
    },

    // ── Registry retrieval (build/registry.ts) ──────────────────────────────
    CLONE_REF_REQUIRED: {
        code: "AX-PROJECT-022",
        title: "No Artifact Named",
        description: "`axon clone` was run without an artifact to clone. Name one, for example: axon clone @axon/arxiv",
        source: "cli",
        severity: "fatal",
    },
    FORK_REF_REQUIRED: {
        code: "AX-PROJECT-023",
        title: "No Artifact Named",
        description: "`axon fork` was run without an artifact to fork. Name one, for example: axon fork @axon/arxiv --as @you/arxiv",
        source: "cli",
        severity: "fatal",
    },
    FORK_NAME_REQUIRED: {
        code: "AX-PROJECT-024",
        title: "Fork Needs A New Name",
        description: "A fork is published under your own namespace, so it needs a name: pass --as <package-name>, for example: axon fork @axon/arxiv --as @you/arxiv",
        source: "cli",
        severity: "fatal",
    },
    CLONE_TARGET_EXISTS: {
        code: "AX-PROJECT-025",
        title: "Clone Target Not Empty",
        description: "The directory the artifact would be cloned into already has files in it. Clone into a new directory, or clear this one first.",
        source: "cli",
        severity: "fatal",
    },
    ARTIFACT_DOWNLOAD_FAILED: {
        code: "AX-PROJECT-026",
        title: "Artifact Download Failed",
        description: "The registry did not serve the artifact's source archive. The version may have been unpublished, or the network request failed.",
        source: "cli",
        severity: "fatal",
    },
    ARTIFACT_EXTRACT_FAILED: {
        code: "AX-PROJECT-027",
        title: "Artifact Extract Failed",
        description: "The downloaded archive could not be unpacked. It may be truncated, or `tar` is unavailable on this machine.",
        source: "cli",
        severity: "fatal",
    },

    // ── Project frame (build/project/) ──────────────────────────────────────
    VERSION_INVALID: {
        code: "AX-PROJECT-028",
        title: "Invalid Version",
        description: "The project's package.json version is not valid semver, so the next version cannot be derived from it. Fix the version field by hand.",
        source: "cli",
        severity: "fatal",
    },
    FRAMEWORK_NOT_INSTALLED: {
        code: "AX-PROJECT-029",
        title: "Framework Packages Not Installed",
        description: "The generated type frame references @arcforge/types, @arcforge/engines and h3, none of which resolve from this project. Run `bun install` before `axon prepare`.",
        source: "cli",
        severity: "fatal",
    },
    CONFIG_EVALUATION_ESCAPED: {
        code: "AX-PROJECT-030",
        title: "defineAgent() Called Outside Config Evaluation",
        description: "defineAgent() ran outside the loader that evaluates axon.config.ts — it is a declaration helper, not a runtime function, and cannot be called from application code.",
        source: "cli",
        severity: "fatal",
    },
    PORT_UNAVAILABLE: {
        code: "AX-PROJECT-031",
        title: "No Free Port",
        description: "Every port in the range the agent scanned is already in use. Stop whatever is holding them, or start the agent on a different port.",
        source: "cli",
        severity: "fatal",
    },

    // ── Subagents (build/agent/agents.ts) ───────────────────────────────────
    PARENT_INSTANCE_NOT_RUNNING: {
        code: "AX-RUNTIME-005",
        title: "Parent Agent Not Running",
        description: "A subagent was requested against a parent session that is no longer live — the parent shut down, crashed, or was never booted by this process.",
        source: "runtime",
        severity: "fatal",
    },
    SUBAGENT_DEPTH_EXCEEDED: {
        code: "AX-RUNTIME-006",
        title: "Subagent Depth Limit Reached",
        description: "An agent tried to spawn a subagent beyond the maximum nesting depth. The limit exists so a recursive delegation cannot spawn processes without bound.",
        source: "runtime",
        severity: "fatal",
    },
    SUBAGENT_CHILD_LIMIT_EXCEEDED: {
        code: "AX-RUNTIME-007",
        title: "Subagent Child Limit Reached",
        description: "One agent tried to hold more live children than the limit allows. Existing children must finish before more can be spawned.",
        source: "runtime",
        severity: "fatal",
    },
    SUBAGENT_DESCENDANT_LIMIT_EXCEEDED: {
        code: "AX-RUNTIME-008",
        title: "Subagent Descendant Limit Reached",
        description: "The whole subagent tree beneath one root exceeded its live-descendant budget. The limit bounds total concurrent processes, not just direct children.",
        source: "runtime",
        severity: "fatal",
    },
    SUBAGENT_REQUEST_INVALID: {
        code: "AX-RUNTIME-009",
        title: "Malformed Subagent Request",
        description: "A subagent request did not carry a usable prompt. It must be an object with `prompt` as a string or an array of strings.",
        source: "runtime",
        severity: "fatal",
    },
    INSTANCE_NOT_LOCAL: {
        code: "AX-RUNTIME-010",
        title: "Agent Instance Is Not Local",
        description: "An operation that only works against a locally booted agent was given a remote one. Subagent spawning and the managed base workspace both require a local process.",
        source: "runtime",
        severity: "fatal",
    },
    HOST_METHOD_UNKNOWN: {
        code: "AX-RUNTIME-011",
        title: "Unknown Host Method",
        description: "A booted agent called a host method this platform does not implement. The agent's framework version is likely newer than the CLI running it.",
        source: "runtime",
        severity: "fatal",
    },

    // ── Self-update (update/) ───────────────────────────────────────────────
    UPDATE_CURRENT_VERSION_INVALID: {
        code: "AX-TUI-029",
        title: "Running Version Is Not Semver",
        description: "The version this app reports for itself is not valid semver, so it cannot be compared against the latest release.",
        source: "cli",
        severity: "fatal",
    },
    UPDATE_RELEASE_INVALID: {
        code: "AX-TUI-030",
        title: "Malformed Release Record",
        description: "The backend's release record did not describe a valid @arcforge/axon `latest` version, so there is nothing safe to update to.",
        source: "cli",
        severity: "fatal",
    },
    UPDATE_UNAVAILABLE_IN_DEVELOPMENT: {
        code: "AX-TUI-031",
        title: "Update Not Available Here",
        description: "Self-update needs the packaged update helper and a supervisor request path, neither of which exists in a source checkout. Update the installed app instead.",
        source: "cli",
        severity: "fatal",
    },
    UPDATE_SUPERVISOR_UNAVAILABLE: {
        code: "AX-TUI-032",
        title: "Update Supervisor Unavailable",
        description: "The running app has no supervisor request path, so it cannot hand an update off to be applied after exit.",
        source: "cli",
        severity: "fatal",
    },
    UPDATE_HELPER_ARGS_INVALID: {
        code: "AX-TUI-033",
        title: "Malformed Update Helper Arguments",
        description: "The update helper was invoked without the --from/--to/--bun/--axon/--state arguments it requires. It is spawned by the app, not run by hand.",
        source: "cli",
        severity: "fatal",
    },
    UPDATE_HELPER_VERSION_INVALID: {
        code: "AX-TUI-034",
        title: "Update Helper Given Bad Versions",
        description: "The update helper received a --from or --to value that is not valid semver, so it refused to install anything.",
        source: "cli",
        severity: "fatal",
    },

    // ── Test runner (test/) ─────────────────────────────────────────────────
    TEST_FILES_NOT_FOUND: {
        code: "AX-TUI-035",
        title: "No Test Files Matched",
        description: "No files matched the requested test patterns, so there was nothing to run. Check the pattern, or the directory it was resolved against.",
        source: "cli",
        severity: "fatal",
    },
    // ── Ollama (services/ollama/) ───────────────────────────────────────────
    OLLAMA_UNAVAILABLE: {
        code: "AX-TUI-037",
        title: "Ollama Is Not Running",
        description: "No Ollama daemon answered on this machine. Start it with `ollama serve`, or install Ollama from https://ollama.com to run models locally.",
        source: "cli",
        severity: "fatal",
    },
    OLLAMA_REQUEST_FAILED: {
        code: "AX-TUI-038",
        title: "Ollama Request Failed",
        description: "The local Ollama daemon is running but refused a request — most often an unknown model name. The daemon's own message is included.",
        source: "cli",
        severity: "fatal",
    },
    OLLAMA_REGISTRY_UNREACHABLE: {
        code: "AX-TUI-039",
        title: "Ollama Registry Unreachable",
        description: "Could not reach the Ollama model registry to look a model up. Downloading needs a network connection; models already on disk still work offline.",
        source: "cli",
        severity: "fatal",
    },
    OLLAMA_PULL_FAILED: {
        code: "AX-TUI-040",
        title: "Model Download Failed",
        description: "Ollama could not finish downloading the model. The name may not exist in the registry, or the transfer was interrupted — a retry resumes from whatever was already fetched.",
        source: "cli",
        severity: "fatal",
    },

    TEST_PRELOAD_MISSING: {
        code: "AX-TUI-036",
        title: "Test API Loaded Without Its Preload",
        description: "The instrumented test API was imported without the preload that installs it. Tests must run through `axon test`, which wires the preload.",
        source: "cli",
        severity: "fatal",
    },
} as const satisfies Record<string, AxonErrorMapEntry>

export type AxonErrorMap = typeof errorMap
export type AxonErrorCode = keyof AxonErrorMap
