import { mkdir, mkdtemp, rm, readFile, writeFile, readdir, unlink } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { Platform } from "@arcforge/platform/platform"
import { Blueprint } from "@arcforge/platform/build/blueprint"
import type { ProjectT } from "@arcforge/platform/build/project"
import { TEST_USER, TEST_VERSION, TEST_FRAMEWORK } from "../../../../setup/user"
import { describe, it, expect, beforeAll, afterAll } from "bun:test"

/**
 * Scaffolded ONCE for the whole file.
 *
 * Every assertion here is about what typegen writes for a given src/tools/
 * directory — the scaffold (which runs a real `bun install`) is setup, not the
 * subject, and paying for it per test made each case ~1s of install to test a
 * few hundred bytes of .d.ts. That put the file at the 5s per-test limit, so it
 * passed alone and failed under a loaded parallel run: a load-dependent result,
 * which is worse than a slow one.
 *
 * The tests stay isolated because `tools()` clears src/tools/ before writing —
 * what varies between them is that directory's contents and nothing else.
 */
let storeDir: string
let dir: string
let project: ProjectT

beforeAll(async () => {
    storeDir = await mkdtemp(join(tmpdir(), "axon-test-store-"))
    dir = await mkdtemp(join(tmpdir(), "axon-test-dir-"))

    const name = `@${TEST_USER.username}/test-agent-${crypto.randomUUID().slice(0, 8)}`
    project = await Platform({ version: TEST_VERSION, ...TEST_FRAMEWORK, store: storeDir }).projects.create("agent", { name, dir })
})

afterAll(async () => {
    await rm(storeDir, { recursive: true, force: true })
    await rm(dir, { recursive: true, force: true })
})

/** Replace src/tools/ with exactly these files, then typegen against a fresh scan. */
async function tools(files: Record<string, string>) {
    // A scaffolded agent is minimal — src/tools/ exists only once the author
    // writes a tool, which is what this helper is standing in for.
    const toolsDir = join(project.root, "src", "tools")
    await mkdir(toolsDir, { recursive: true })
    for (const existing of await readdir(toolsDir).catch(() => [])) {
        await unlink(join(toolsDir, existing))
    }
    // .agent/ is regenerated by typegen, but tool-globals.d.ts is only WRITTEN
    // when there is at least one tool — a stale file from a previous case would
    // otherwise satisfy the "no tools" assertion below.
    await rm(join(project.root, ".agent", "types", "tool-globals.d.ts"), { force: true })

    for (const [name, contents] of Object.entries(files)) {
        await writeFile(join(toolsDir, name), contents)
    }

    const { blueprint } = await Blueprint({ root: project.root }).load()
    return project.typegen(blueprint)
}

function dts(): Promise<string> {
    return readFile(join(project.root, ".agent", "types", "tool-globals.d.ts"), "utf-8")
}

describe("agent project: typegen() tool-globals.d.ts", () => {
    it("an agent with no tools — count is 0, no tool-globals.d.ts written", async () => {
        const result = await tools({})

        expect(result.toolGlobals).toBe(0)
        await expect(dts()).rejects.toThrow()
    })

    it("a real exported function in src/tools/ becomes a typed top-level global", async () => {
        const result = await tools({
            "math.ts": "export function add(a: number, b: number): number { return a + b }\n",
        })

        // Promise<number>, not number: the capsule wraps every tool in an
        // async mediation wrapper, so the value the author's scripts and
        // the agent both call returns a Promise whatever was written here.
        // Declaring the unwrapped type gave editors autocomplete that
        // disagreed with the runtime.
        expect(result.toolGlobals).toBe(1)
        expect(await dts()).toContain("function add(a: number, b: number): Promise<number>")
    })

    it("carries the function's JSDoc comment into the generated declaration", async () => {
        await tools({
            "math.ts": "/** Adds two numbers together. */\nexport function add(a: number, b: number): number { return a + b }\n",
        })

        expect(await dts()).toContain("Adds two numbers together.")
    })

    it("multiple exported functions in one file are each declared as their own global", async () => {
        const result = await tools({
            "math.ts": "export function add(a: number, b: number): number { return a + b }\nexport function sub(a: number, b: number): number { return a - b }\n",
        })

        expect(result.toolGlobals).toBe(2)
        expect(await dts()).toContain("function add(a: number, b: number): Promise<number>")
        expect(await dts()).toContain("function sub(a: number, b: number): Promise<number>")
    })

    it("does not scan test files inside src/tools/", async () => {
        const result = await tools({
            "math.test.ts": "export function shouldNotAppear(): void {}\n",
        })

        expect(result.toolGlobals).toBe(0)
    })
})
