import type { AxonScope } from "@arcforge/types"

/**
 * scopeToDts — the agent's executable scope, spelled as TypeScript.
 *
 * The sibling spelling of renderScope(): same AxonScope in, same members
 * out, different audience. renderScope() writes the <scope> block the model
 * reads; this writes the ambient declarations an editor reads, so tool
 * calls in the author's own src/tools, src/scripts, hooks, and routes
 * typecheck against exactly what the capsule will provide.
 *
 * These two must never disagree about WHAT is in scope. They cannot,
 * because neither decides it — toScope() does, once, and both render its
 * result. This file only chooses how to spell it for `tsc`:
 *
 *   flat module        → each member declared directly (a top-level global)
 *   namespaced module  → `namespace <name> { ... }`
 *
 * No `declare` prefix on members: everything inside `declare global { }` is
 * already ambient, and TS1038 rejects a nested `declare` there.
 */
export function scopeToDts(scope: AxonScope): string {
    const modules = scope.modules.filter(module => module.members.length > 0)

    const lines: string[] = [
        "// tool-globals.d.ts — generated by axon prepare, do not edit",
        "// Every tool the capsule can call, declared as it is callable.",
        "// Mirrors the <scope> block the model receives — same source, same members.",
        "",
        "declare global {",
    ]

    // Ambient types first and deduped by exact text: a member declaration
    // referencing Promise<DeployStatus> is unresolvable without it, in an
    // editor exactly as in the model's context.
    for (const ambient of new Set(modules.flatMap(module => module.ambientTypes ?? []))) {
        lines.push(indent(ambient), "")
    }

    for (const module of modules) {
        if (module.description) lines.push(indent(jsdocBlock(module.description)))

        if (module.flat) {
            for (const member of module.members) {
                if (member.jsdoc) lines.push(indent(jsdocBlock(member.jsdoc)))
                lines.push(indent(member.declaration))
            }
            continue
        }

        const body: string[] = []
        for (const member of module.members) {
            if (member.jsdoc) body.push(jsdocBlock(member.jsdoc))
            body.push(member.declaration)
        }
        lines.push(indent(`namespace ${module.name} {\n${indent(body.join("\n"))}\n}`))
    }

    lines.push("}", "", "export {}", "")
    return lines.join("\n")
}

/** How many callable members this scope declares — the caller's "did anything land" signal. */
export function scopeMemberCount(scope: AxonScope): number {
    return scope.modules.reduce((total, module) => total + module.members.length, 0)
}

function indent(text: string): string {
    return text.split("\n").map(line => (line ? `    ${line}` : line)).join("\n")
}

function jsdocBlock(text: string): string {
    const lines = text.split("\n")
    if (lines.length === 1) return `/** ${text} */`
    return `/**\n${lines.map(l => ` * ${l}`.trimEnd()).join("\n")}\n */`
}
