// .agent/prompts.d.ts — generated by axon prepare, do not edit
// Re-run `axon prepare` after adding or modifying prompts.

import "@axon/types"
declare module "@axon/types" {
    interface AxonPromptMap {
        /** Props: kanbanRoot?:string */
        "KanbanSchool": { kanbanRoot?: string }
    }
}

export {}
