// Generated by axon prepare — do not edit.
// Ambient globals for cognet source. Implemented by the compile host
// (@arcforge/cognet); typed here for the editor.
import type {
    AxonStimulusEntry,
    CognetConfig,
    CognetPlugin,
    KernelAbi,
    EngineType,
} from "@arcforge/types"
import type { EcsT } from "@arcforge/cognet/ecs"

declare global {
    /** what this brain declares (mode, wakeOn, engines) — cognet.config.ts only.
     *  Identity is NOT declared: name and version come from package.json. */
    function defineCognet<T extends CognetConfig>(config: T): T

    /**
     * A lifecycle plugin — plumbing wired to hooks (boot, wake, tick,
     * shutdown), declared in plugins/*.ts. Registers at import time, before
     * the brain boots. PLUMBING ONLY: load/save derived state, warm caches,
     * devtools. Domain facts are stimuli that fold into the world, never hooks.
     */
    function definePlugin(plugin: CognetPlugin): CognetPlugin

    /**
     * THE entry point — declare the tick pipeline once, in src/main.ts.
     * The kernel wakes it per stimulus batch; ticks run until stop() or
     * interrupt. Wake-scoped things arrive as args, never as globals.
     */
    function loop(body: (ctx: {
        /** stimuli committed since the last wake, in seq order — stimulus:* only, the cognet's whole input contract */
        stimuli: readonly AxonStimulusEntry[]
        /** kernel interrupt — honor it between units of work */
        signal: AbortSignal
        /** end the wake after this tick — the brain stays warm */
        stop(): void
    }) => Promise<void> | void): void

    /** the syscall table — live from load() onward; do work inside loop(), not at module top level */
    /** Engine role names and call shapes generated from cognet.config.ts. */
    interface CognetEngineRequirements {
        [role: string]: { type: EngineType }

    }

    const kernel: KernelAbi<CognetEngineRequirements>


    /** a named stage within a tick — cognet:phase:* telemetry */
    function phase<T>(name: string, fn: () => Promise<T>): Promise<T>

    /** a unit of work within a phase — timed for the flame graph */
    function system<T>(name: string, fn: () => Promise<T>): Promise<T>

    /**
     * The world — entities, components, and queries over both.
     *
     * The brain's short-term memory: it lives as long as the cognet does, not
     * as long as a wake, so a decaying drive or a remembered place survives
     * from one tick to the next. Every write commits to the session log with
     * its value, which is what makes the world reconstructible afterwards.
     *
     * Built on first touch — a cognet that never reaches for it carries no
     * entity store. Declare a component's shape once with `ecs.declare()` so
     * readers can render it honestly.
     */
    const ecs: EcsT
}

export {}
