// Generated by axon prepare — do not edit.
// Ambient globals for cognet source. Implemented by the compile host
// (@arcforge/cognet); typed here for the editor.
import type {
    AxonStimulusEntry,
    CognetConfig,
    CognetPlugin,
    KernelAbi,
} from "@arcforge/types"

declare global {
    /** identity declaration — cognet.config.ts only */
    function defineCognet<T extends CognetConfig>(config: T): T

    /**
     * A lifecycle plugin — plumbing wired to hooks (boot, wake, tick,
     * shutdown), declared in plugins/*.ts. Registers at import time, before
     * the brain boots. PLUMBING ONLY: load/save derived state, warm caches,
     * devtools. Domain facts are stimuli that fold into the world, never hooks.
     */
    function definePlugin(plugin: CognetPlugin): CognetPlugin

    /**
     * THE entry point — declare the tick pipeline once, in src/main.ts.
     * The kernel wakes it per stimulus batch; ticks run until stop() or
     * interrupt. Wake-scoped things arrive as args, never as globals.
     */
    function loop(body: (ctx: {
        /** stimuli committed since the last wake, in seq order — stimulus:* only, the cognet's whole input contract */
        stimuli: readonly AxonStimulusEntry[]
        /** kernel interrupt — honor it between units of work */
        signal: AbortSignal
        /** end the wake after this tick — the brain stays warm */
        stop(): void
    }) => Promise<void> | void): void

    /** the syscall table — live from load() onward; do work inside loop(), not at module top level */
    const kernel: KernelAbi


    /** a named stage within a tick — cognet:phase:* telemetry */
    function phase<T>(name: string, fn: () => Promise<T>): Promise<T>

    /** a unit of work within a phase — timed for the flame graph */
    function system<T>(name: string, fn: () => Promise<T>): Promise<T>
}

export {}
