import type { AxonScope } from "@arcforge/types"

/**
 * scopeToDts — the agent's executable scope, spelled as TypeScript.
 *
 * The sibling spelling of renderScope(): same AxonScope in, same members
 * out, different audience. renderScope() writes the <scope> block the model
 * reads; this writes the ambient declarations an editor reads, so tool
 * calls in the author's own src/tools, src/scripts, hooks, and routes
 * typecheck against exactly what the capsule will provide.
 *
 * These globals are real in host-side code, not only inside the capsule:
 * Inject().runtime() binds each one to the matching axon.tools.* proxy when
 * the runtime comes up (see core/src/platform/inject.ts). That is what makes
 * this file honest — for a while it declared globals a script could not
 * actually call, so `kanban.list()` typechecked and then threw at runtime.
 *
 * These two must never disagree about WHAT is in scope. They cannot,
 * because neither decides it — toScope() does, once, and both render its
 * result. This file only chooses how to spell it for `tsc`:
 *
 *   flat module        → each member declared directly (a top-level global)
 *   namespaced module  → `namespace <name> { ... }`
 *
 * No `declare` prefix on members: everything inside `declare global { }` is
 * already ambient, and TS1038 rejects a nested `declare` there.
 */
export function scopeToDts(scope: AxonScope): string {
    const modules = scope.modules.filter(module => module.members.length > 0)

    const lines: string[] = [
        "// tool-globals.d.ts — generated by axon prepare, do not edit",
        "// Every tool the capsule can call, declared as it is callable.",
        "// Mirrors the <scope> block the model receives — same source, same members.",
        "",
        "declare global {",
    ]

    // Ambient types first and deduped by exact text: a member declaration
    // referencing Promise<DeployStatus> is unresolvable without it, in an
    // editor exactly as in the model's context.
    for (const ambient of new Set(modules.flatMap(module => module.ambientTypes ?? []))) {
        lines.push(indent(ambient), "")
    }

    for (const module of modules) {
        if (module.description) lines.push(indent(jsdocBlock(module.description)))

        /**
         * Every member is declared DIRECTLY, whatever its origin.
         *
         * A module's tools used to be wrapped in `namespace <tool name> { … }`,
         * mirroring a runtime that placed them under that name. Both sides have
         * stopped: placement is unconditional now (see core's Tools.globals),
         * because a tool file exporting `const fs = {…}` is already its own
         * namespace, and wrapping it again declared `fs.fs.read()` — a path an
         * editor accepted, a model read off these very types and called, and
         * the runtime did not have.
         *
         * The spelling is no longer a decision this file makes. It emits what
         * the runtime installs, member for member, which is the only version
         * that cannot drift from it.
         */
        for (const member of module.members) {
            if (member.jsdoc) lines.push(indent(jsdocBlock(member.jsdoc)))
            lines.push(indent(member.declaration))
        }
    }

    lines.push("}", "", "export {}", "")
    return lines.join("\n")
}

/** How many callable members this scope declares — the caller's "did anything land" signal. */
export function scopeMemberCount(scope: AxonScope): number {
    return scope.modules.reduce((total, module) => total + module.members.length, 0)
}

function indent(text: string): string {
    return text.split("\n").map(line => (line ? `    ${line}` : line)).join("\n")
}

function jsdocBlock(text: string): string {
    const lines = text.split("\n")
    if (lines.length === 1) return `/** ${text} */`
    return `/**\n${lines.map(l => ` * ${l}`.trimEnd()).join("\n")}\n */`
}
