import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { Platform } from "@arcforge/platform/platform"
import { TEST_USER, TEST_VERSION, TEST_FRAMEWORK } from "../../../setup/user"
import { describe, it, expect } from "bun:test"

/**
 * What a published prompt package actually contains.
 *
 * A prompt ships as source — the folder IS the artifact — so the bundle is
 * the whole product. Two things have to travel that a fixed layout would
 * miss: `components/` (fragments the prompts compose) and `README.md` (the
 * page the registry renders). The generated frame must NOT travel.
 */

function disposableName(): string {
    return `@${TEST_USER.username}/test-prompt-${crypto.randomUUID().slice(0, 8)}`
}

/** Entry paths inside a bundled tarball, with the leading `package/` stripped. */
async function tarballEntries(tarball: string): Promise<string[]> {
    const proc = Bun.spawn(["tar", "-tzf", tarball], { stdout: "pipe", stderr: "pipe" })
    const out = await new Response(proc.stdout).text()
    await proc.exited
    return out
        .split("\n")
        .filter(Boolean)
        .map(entry => entry.replace(/^package\//, ""))
        .filter(entry => entry !== "" && !entry.endsWith("/"))
}

async function withPrompt(
    build: (root: string) => Promise<void>,
    fn: (ctx: { entries: string[]; image: Record<string, unknown> }) => Promise<void>,
): Promise<void> {
    const storeDir = await mkdtemp(join(tmpdir(), "axon-test-store-"))
    const dir = await mkdtemp(join(tmpdir(), "axon-test-prompt-"))
    try {
        const platform = Platform({ version: TEST_VERSION, ...TEST_FRAMEWORK, store: storeDir })
        const project = await platform.projects.create("prompt", { name: disposableName(), dir })
        await build(project.root)

        const artifact = await project.bundle()
        const entries = await tarballEntries(artifact.tarball)
        await fn({ entries, image: artifact.image as unknown as Record<string, unknown> })
    } finally {
        await rm(storeDir, { recursive: true, force: true })
        await rm(dir, { recursive: true, force: true })
    }
}

describe("prompt package: bundle", () => {
    it("ships every top-level prompt, in both formats", async () => {
        await withPrompt(
            async root => {
                await writeFile(join(root, "second.vue"), "<template><p>second</p></template>\n")
                await writeFile(join(root, "third.md"), "third\n")
            },
            async ({ entries }) => {
                expect(entries).toContain("second.vue")
                expect(entries).toContain("third.md")
                expect(entries).toContain("prompt.config.ts")
                expect(entries).toContain("package.json")
            },
        )
    }, 60_000)

    it("ships components/ — the fragments prompts compose", async () => {
        await withPrompt(
            async root => {
                await mkdir(join(root, "components"), { recursive: true })
                await writeFile(
                    join(root, "components", "shared.vue"),
                    "<template><p>shared</p></template>\n",
                )
            },
            async ({ entries }) => {
                expect(entries).toContain("components/shared.vue")
            },
        )
    }, 60_000)

    it("ships README.md — the page the registry renders", async () => {
        await withPrompt(
            async root => {
                await writeFile(join(root, "README.md"), "# a prompt\n")
            },
            async ({ entries }) => {
                expect(entries).toContain("README.md")
            },
        )
    }, 60_000)

    it("does not ship the generated type frame", async () => {
        await withPrompt(
            async () => {},
            async ({ entries }) => {
                // The frame is machine-local: regenerated by prepare, and
                // meaningless to a consumer who installs the package.
                expect(entries.some(entry => entry.startsWith(".prompt/"))).toBe(false)
                expect(entries).not.toContain("tsconfig.json")
            },
        )
    }, 60_000)

    it("carries the description into the image, for the registry card", async () => {
        await withPrompt(
            async root => {
                const pkg = JSON.parse(await Bun.file(join(root, "package.json")).text()) as Record<string, unknown>
                pkg.description = "does one useful thing"
                await writeFile(join(root, "package.json"), JSON.stringify(pkg, null, 4) + "\n")
            },
            async ({ image }) => {
                expect(image.kind).toBe("prompt")
                expect(image.description).toBe("does one useful thing")
                expect(image.public).toBe(true)
            },
        )
    }, 60_000)
})
