// .agent/axon.d.ts — generated by axon prepare — do not edit
// Re-run `axon prepare` after upgrading the axon framework.
import type { AxonHandle, UiHandle, LiveProcHandle } from "@axon/types"

declare global {
    namespace NodeJS {
        // ── Axon-injected env vars ────────────────────────────────────────────
        interface ProcessEnv {
            /**
             * Absolute path to the agent's own directory. Injected by the Axon
             * runtime into every capsule — always present, never undefined.
             *
             * Use it to anchor paths into data/, knowledge/, workspace/:
             * ```ts
             * const workspace = `${process.env.AXON_HOME}/data/workspace`
             * ```
             */
            AXON_HOME: string
        }

        // ── process.run() / process.spawn() ──────────────────────────────────
        // The capsule extends the global process object with two safe execution APIs.
        // process.exit() is blocked — the capsule manages its own lifecycle.
        interface Process {
            /**
             * Run a shell command and wait for it to complete. Never throws — errors are
             * returned in the result object.
             *
             * ```ts
             * const { ok, stdout, stderr } = await process.run("git status")
             * if (!ok) console.error(stderr)
             * ```
             *
             * @see https://axon.arclabs.it/docs/v2/api/proc/run
             */
            run(
                command: string,
                opts?: { cwd?: string; env?: Record<string, string>; input?: string }
            ): Promise<{ ok: boolean; exitCode: number; stdout: string; stderr: string; err?: string }>

            /**
             * Spawn a long-running process. Returns a handle immediately — the process
             * runs in the background and is visible in the agent's process list.
             *
             * ```ts
             * const server = process.spawn("bun dev")
             * await server.waitFor("ready", { timeoutMs: 10_000 })
             * const logs = server.stdout()
             * server.kill()
             * ```
             *
             * @see https://axon.arclabs.it/docs/v2/api/proc/spawn
             */
            spawn(
                command: string,
                opts?: { cwd?: string; env?: Record<string, string> }
            ): LiveProcHandle
        }
    }

    // ── Axon runtime globals ──────────────────────────────────────────────

    /**
     * The live Axon runtime handle. Available as a global in tools, scripts,
     * hooks, and server routes — no import needed.
     *
     * Everything the agent can do is accessed through this object: sending
     * requests, managing threads, calling tools, running scripts, and
     * reacting to lifecycle events.
     *
     * **One-shot request** — waits for the full cognitive loop to complete:
     * ```ts
     * const result = await axon.request("summarise the project")
     * console.log(result.text)
     * ```
     *
     * **Streaming** — receive entries as they are produced:
     * ```ts
     * const { stream } = axon.stream("explain the build system")
     * for await (const entry of stream) {
     *     if (entry.type === "axon:agent:message:delta") {
     *         process.stdout.write(entry.payload.content)
     *     }
     * }
     * ```
     *
     * **Threads** — sequential calls share context automatically.
     * Named threads let you run isolated side tasks without affecting the
     * main conversation:
     * ```ts
     * // These three calls form a single conversation — the agent sees each
     * // in context of the previous ones:
     * await axon.request("hello")
     * await axon.request("what did I just say?")
     * await axon.request("now summarise our conversation")
     *
     * // Fork into a named thread for an isolated side task:
     * const { text } = await axon.request({
     *     prompt: "what is the capital of France?",
     *     thread: "geo-lookup",
     * })
     *
     * // Or pin a handle for repeated use on the same thread:
     * const research = axon.thread("research")
     * await research.request("find everything about the Eiffel Tower")
     * await research.request("summarise the construction history")
     * console.log(research.entries) // full timeline for this thread
     * ```
     *
     * @see https://axon.arclabs.it/docs/v2/api
     * @see https://axon.arclabs.it/docs/v2/api/thread
     * @see https://axon.arclabs.it/docs/v2/api/stream
     */
    const axon: AxonHandle

    /**
     * UI bridge. Post notifications, prompts, and content injections to the
     * connected TUI client. All methods are fire-and-forget in headless mode —
     * they never throw if no client is connected.
     *
     * @see https://axon.arclabs.it/docs/v2/api/ui
     */
    const ui: UiHandle

    /**
     * Named arguments passed to the current script invocation.
     * Typed via `defineArgs()` — use that for full type safety.
     *
     * ```ts
     * const { date } = defineArgs<{ date: string }>()
     * ```
     *
     * @see https://axon.arclabs.it/docs/v2/api/scripts
     */
    const args: Record<string, string>

    // ── Test globals ────────────────────────────────────────────────────

    /**
     * Boot a full Axon runtime for integration testing. Global — no import needed.
     *
     * ```ts
     * const { axon, stop } = await Axon()
     * const result = await axon.request("hello")
     * await stop()
     * ```
     *
     * @see https://axon.arclabs.it/docs/v2/agent/testing
     */
    const Axon: typeof import("@axon/test").Axon

    // ── Agent / module authoring ──────────────────────────────────────────

    /**
     * Define this agent's identity, engine, and configuration.
     * Used as the default export in `axon.config.ts`.
     *
     * @see https://axon.arclabs.it/docs/v2/agent/config
     */
    const defineAgent: typeof import("@axon/types").defineAgent

    /**
     * Define a reusable module. Used as the default export in `module.config.ts`.
     *
     * @see https://axon.arclabs.it/docs/v2/modules/config
     */
    const defineModule: typeof import("@axon/types").defineModule

    /**
     * Declare the expected argument shape for this script. Stripped at runtime —
     * type-only. Returns the args object cast to your type.
     *
     * ```ts
     * const { userId, limit } = defineArgs<{ userId: string; limit?: number }>()
     * ```
     *
     * @see https://axon.arclabs.it/docs/v2/api/scripts
     */
    function defineArgs<T extends Record<string, unknown>>(): T

    /**
     * Declare the expected prop shape for this prompt template. Stripped at
     * runtime — type-only. Used in `src/prompts/` files.
     *
     * @see https://axon.arclabs.it/docs/v2/api/prompt
     */
    function defineProps<T extends Record<string, unknown>>(): void

    // ── Server plugin registration ────────────────────────────────────────

    /**
     * Register a server plugin. Extend the agent's HTTP/WebSocket server with
     * custom routes and handlers.
     *
     * @see https://axon.arclabs.it/docs/v2/agent/server
     */
    const defineAxonPlugin: typeof import("@axon/server").defineAxonPlugin

    // ── Engine adapters ───────────────────────────────────────────────────

    /**
     * Axon Cloud inference. Requires `AXON_ENGINE_API_KEY`.
     *
     * ```ts
     * export default defineAgent({ engine: Axon({ model: "axon-astra-v1" }) })
     * ```
     */
    const Axon: typeof import("@axon/engines").Axon

    /**
     * Ollama local inference.
     *
     * ```ts
     * export default defineAgent({ engine: Ollama({ model: "qwen2.5:7b" }) })
     * ```
     */
    const Ollama: typeof import("@axon/engines").Ollama

    /**
     * OpenAI Codex / GPT inference.
     *
     * ```ts
     * export default defineAgent({ engine: Codex({ model: "o3" }) })
     * ```
     */
    const Codex: typeof import("@axon/engines").Codex

    /**
     * OpenRouter inference. Routes to any provider.
     *
     * ```ts
     * export default defineAgent({ engine: OpenRouter({ model: "anthropic/claude-sonnet-4-5" }) })
     * ```
     */
    const OpenRouter: typeof import("@axon/engines").OpenRouter

    /**
     * Mock engine for tests. Responds with a fixed or handler-driven AIR string —
     * no network, no API key required.
     *
     * ```ts
     * const { axon, stop } = await Axon({ engine: Mock() })
     * ```
     *
     * @see https://axon.arclabs.it/docs/v2/agent/testing
     */
    const Mock: typeof import("@axon/engines").Mock

    // ── H3 Event Handler API ──────────────────────────────────────────────
    const defineEventHandler: typeof import("h3").defineEventHandler
    const defineWebSocketHandler: typeof import("h3").defineWebSocketHandler
    const eventHandler: typeof import("h3").eventHandler

    // ── H3 Request Utilities ──────────────────────────────────────────────
    const getRouterParam: typeof import("h3").getRouterParam
    const getRouterParams: typeof import("h3").getRouterParams
    const getQuery: typeof import("h3").getQuery
    const readBody: typeof import("h3").readBody
    const getRequestURL: typeof import("h3").getRequestURL
    const getRequestHost: typeof import("h3").getRequestHost

    // ── H3 Headers ────────────────────────────────────────────────────────
    const getHeader: typeof import("h3").getHeader
    const getHeaders: typeof import("h3").getHeaders
    const setHeader: typeof import("h3").setHeader
    const setResponseHeader: typeof import("h3").setResponseHeader

    // ── H3 Cookies ───────────────────────────────────────────────────────
    const getCookie: typeof import("h3").getCookie
    const setCookie: typeof import("h3").setCookie
    const deleteCookie: typeof import("h3").deleteCookie

    // ── H3 Response Helpers ───────────────────────────────────────────────
    const createError: typeof import("h3").createError
    const send: typeof import("h3").send
    const sendRedirect: typeof import("h3").sendRedirect
    const sendStream: typeof import("h3").sendStream
    const isError: typeof import("h3").isError
}

export {}
